# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbcbc5582edac4993bb9fc90196dea8238378a59fcd1ce000a157ca9e5ff7820805fa1f6bacbe0ec1245b8264dddab8cc31444135022484f5ee852ae4e444b2

test:
  secret_key_base: 9333743c1d861c640d3a11b17102fbdeef1723f09ae8a5db5444839cf7ea7658978541bf631a7b6a2c73bc4e43a8fe3b80ef566d6395dcef02e0fac09f938773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
